#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "abort-install" ]; then
    echo "Installation terminated: Steam License Agreement was DECLINED."
    db_purge
    exit 0
fi

if [ "$1" = "purge" ]; then
    db_input high steam/purge || true
    db_go
fi

# Automatically added by dh_installdebconf/11.3.2ubuntu1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

